version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: uuid
    versions:
    - "> 0.5.1"
  - dependency-name: object
    versions:
    - 0.23.0
  - dependency-name: core-foundation-sys
    versions:
    - 0.8.2
  - dependency-name: cfg-if
    versions:
    - 1.0.0
  - dependency-name: core-foundation
    versions:
    - 0.9.1
